Script started on 廿十八年三月十八日 (週日) 十一時廿六分四秒
]0;pd2vm@pd2-vbox: ~/lab1[01;32mpd2vm@pd2-vbox[00m:[01;34m~/lab1[00m$ make lab1
g++     lab1.cpp   -o lab1
]0;pd2vm@pd2-vbox: ~/lab1[01;32mpd2vm@pd2-vbox[00m:[01;34m~/lab1[00m$ ./lab1
input an integer: 
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 ]0;pd2vm@pd2-vbox: ~/lab1[01;32mpd2vm@pd2-vbox[00m:[01;34m~/lab1[00m$ exit
exit

Script done on 廿十八年三月十八日 (週日) 十一時廿六分廿二秒
